name: DevSecOps CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  sonar-cloud-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=Prayas-sharmaa_DevSecOps
            -Dsonar.organization=prayas-sharmaa

  python-build:
    runs-on: ubuntu-latest
    needs: sonar-cloud-build
    strategy:
      matrix:
        python-version: ['3.10']

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: python manage.py test

  docker-build:
    runs-on: ubuntu-latest
    needs: python-build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/storemanagement:latest

  Infrastructure:
    runs-on: ubuntu-latest
    needs: docker-build

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      AWS_REGION: us-east-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Check EB environment
        id: ebe_check
        run: |
          if aws elasticbeanstalk describe-environments \
              --region $AWS_REGION \
              --environment-names "storemanagement-env" >/dev/null 2>&1; then
              echo "exists=true" >> $GITHUB_OUTPUT
          else
              echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Apply Terraform (deploy only once)
        if: steps.ebe_check.outputs.exists == 'false'
        run: |
          cd terraform
          terraform init
          terraform validate
          terraform plan -out=tfplan
          terraform apply -auto-approve tfplan

      - name: Terraform skipped
        if: steps.ebe_check.outputs.exists == 'true'
        run: echo "Elastic Beanstalk already deployed â€” skipping Terraform."

  ansible-deploy:
    runs-on: ubuntu-latest
    needs: Infrastructure

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      AWS_REGION: us-east-1
      DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Ansible + dependencies
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Install required Ansible roles
        run: |
          ansible-galaxy install -r ansible/requirements.yml

      - name: Prepare SSH key for Ansible
        run: |
          echo "${{ secrets.EB_SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Run Datadog Playbook
        run: |
          ansible-playbook \
            -i ansible/inventories/hosts.ini \
            --key-file private_key.pem \
            ansible/playbooks/configure_datadog.yml
